<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Order #{{ $order->id }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #fff;
            color: #333;
        }

        .container {
            width: 700px;
            margin: auto;
            padding: 30px;
            border: 1px solid #ccc;
        }

        .header,
        .footer {
            text-align: center;
            margin-bottom: 20px;
        }

        .header img {
            width: 80px;
            float: left;
        }

        .header h1 {
            margin: 0;
            font-size: 22px;
        }

        .header p {
            margin: 2px;
            font-size: 13px;
        }

        h2.title {
            text-align: center;
            margin-top: 20px;
            margin-bottom: 20px;
            font-size: 20px;
            text-transform: uppercase;
            border-top: 1px solid #aaa;
            border-bottom: 1px solid #aaa;
            padding: 8px 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 13px;
            margin-bottom: 20px;
        }

        table th,
        table td {
            border: 1px solid #ddd;
            padding: 8px;
        }

        table th {
            background-color: #f5f5f5;
            text-align: left;
        }

        .info-table td {
            border: none;
            padding: 4px 8px;
        }

        .total {
            font-weight: bold;
            font-size: 14px;
            text-align: right;
        }

        .signature-section {
            margin-top: 40px;
            display: flex;
            justify-content: space-between;
        }

        .signature-block {
            width: 45%;
            text-align: center;
        }

        .signature-block .line {
            border-top: 1px solid #333;
            margin-top: 40px;
        }

        .text-muted {
            color: #777;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="header">
            <img src="{{ asset('/storage/' . setting('company_logo')) }}" style="width: 80px; height: auto;" alt="Logo">
            <h1>{{ setting('company_name') }}</h1>
            <p>{{ setting('address') }}</p>
            <p>Phone: {{ setting('company_phone') }}</p>
        </div>

        <h2 class="title">Order</h2>

        <table class="info-table">
            <tr>
                <td><strong>Order ID:</strong> {{ $order->id }}</td>
                <td><strong>Date:</strong> {{ $order->order_date }}</td>
            </tr>
            <tr>
                <td><strong>Branch:</strong> {{ $order->branch?->name ?? 'N/A' }}</td>
                <td><strong>Manager:</strong> {{ $order->customer?->name ?? 'N/A' }}</td>
            </tr>
        </table>

        <table>
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Unit</th>
                    <th colspan="2">Quantity</th>
                    {{-- <th>Price</th> --}}
                    {{-- <th>Subtotal</th> --}}
                </tr>
            </thead>
            <tbody>
                @foreach ($order->orderDetails as $item)
                    <tr>
                        <td>{{ $item->product?->name ?? '-' }}</td>
                        <td>{{ $item->unit?->name ?? '-' }}</td>
                        <td colspan="2">{{ $item->available_quantity }}</td>
                        {{-- <td>{{ number_format($item->price, 2) }}</td> --}}
                        {{-- <td>{{ number_format($item->available_quantity * $item->price, 2) }}</td> --}}
                    </tr>
                @endforeach
                {{-- <tr>
                    <td colspan="4" class="total">Total Amount</td>
                    <td class="total">{{ number_format($order->total_amount, 2) }}</td>
                </tr> --}}
            </tbody>
        </table>
 

        <div class="footer">
            <p class="text-muted">Generated by {{ setting('company_name') }} on {{ now()->format('Y-m-d') }}</p>
        </div>
    </div>
</body>

</html>
