<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QR Code Print Sheet</title>
    <style>
        @page {
            size: A4;
            margin: 15mm;
        }

        body {
            font-family: Arial, sans-serif;
            text-align: center;
            margin: 40px;
        }

        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 2px solid #000;
            padding-bottom: 10px;
            margin-bottom: 15px;
        }

        .logo {
            width: 50px;
            height: 50px;
        }

        .title {
            font-size: 20px;
            font-weight: bold;
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 12px;
            border-top: 2px solid #000;
            padding-top: 5px;
            margin-top: 10mm;
        }

        /* .container {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 10mm;
            padding: 10mm;
        } */

        .qr-block {
            /* width: 55mm;
            height: 75mm;
            text-align: center;
            border: 1px solid #ddd;
            padding: 5mm;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1); */
            margin-top: 150px;

        }

        .qr-code {
            /* width: 50mm;
            height: 50mm; */
        }

        .qr-block svg {
            width: 400px;
            height: 400px;
            border: 1px solid black;
            padding: 20px;
            border-radius: 20px;
        }

        .label {
            font-size: 12px;
            margin-top: 5mm;
            font-weight: bold;
        }

        @media print {
            body {
                margin: 0;
                padding: 20px;
            }

            .container {
                page-break-inside: avoid;
            }

            .footer {
                position: fixed;
                bottom: 0;
            }
        }
    </style>
</head>

<body>

    <!-- Header -->
    <div class="header">
        <img src="{{ url('/') . '/storage/logo/default.png' }}" alt="Workbench Logo" class="logo">
        <div class="title">{{ $qrCode['name'] }}</div>
        <div class="date">{{ now()->format('d M Y') }}</div>
    </div>

    <!-- QR Code Grid -->
    <div class="container">
        <div class="qr-block">
            {!! QrCode::size(200)->generate($qrCode['data']) !!}

        </div>
    </div>

    <!-- Footer -->
    <div class="footer">
        Generated by Workbench | {{ now()->format('H:i A') }}
    </div>

</body>

</html>
